# fly.toml app configuration file generated for hackathon-icy-glade-4419 on 2025-07-19T13:19:00-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vibeseq'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 4567
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
